# https://arthurdenner.medium.com/run-checks-for-flutter-projects-with-github-actions-ba7fa9b357e1
name: Flutter Tests

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  tests:
    if: ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: "2.10.2"
      - name: Restore packages
        run: flutter pub get
      - name: Run tests
        run: flutter test
